import { blogClusters, getPostBySlug } from "@/data/blog-clusters";
import ArticleTemplate from "@/components/blog/ArticleTemplate";
import { notFound } from "next/navigation";

export async function generateMetadata({ params }) {
    const { category, slug } = await params;
    const post = getPostBySlug(slug);

    if (!post) return {};

    return {
        title: post.title,
        description: post.excerpt,
    };
}

export function generateStaticParams() {
    const params = [];
    Object.values(blogClusters).forEach((cluster) => {
        cluster.posts.forEach((post) => {
            params.push({
                category: cluster.slug,
                slug: post.slug,
            });
        });
    });
    return params;
}

export default async function BlogPost({ params }) {
    const { category, slug } = await params;

    // Try manual post first
    let post = getPostBySlug(slug);
    let content = "";

    // If not manual, check generated
    if (!post) {
        const { generatedContent } = await import("@/data/generated-posts");
        const genPost = generatedContent[slug];
        if (genPost) {
            post = {
                ...genPost,
                category: {
                    slug: genPost.category,
                    title: genPost.category.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())
                }
            };
            content = genPost.content;
        }
    } else {
        // Wiring for manual posts (if we had separate content files, we'd load them here)
        // For manual posts in this architecture, content might be in the object or separate.
        // The previous implementation utilized `generated-posts` even for manual placeholders.
        const { generatedContent } = await import("@/data/generated-posts");
        content = generatedContent[slug]?.content || "";
    }

    if (!post) {
        notFound();
    }

    return (
        <ArticleTemplate
            title={post.title}
            intro={post.excerpt + " This comprehensive guide covers everything you need to know about " + post.title.toLowerCase() + "."}
            category={post.category}
            lastUpdated={new Date().toISOString()}
            relatedTools={[
                { label: "Compress Images Online", href: "/image/compressor" },
                { label: "Convert Image Formats", href: "/image/converter" }
            ]}
            faqs={[
                {
                    question: `Why is ${post.title.split(":")[0]} important?`,
                    answer: "It is crucial for web performance, SEO, and user experience. Faster load times lead to better rankings and happier users."
                },
                {
                    question: "How can I implement this?",
                    answer: "You can use automated tools like WebPify or command-line utilities. For best results, integrate it into your build process."
                }
            ]}
        >
            <div dangerouslySetInnerHTML={{ __html: content }} />

            {!content && (
                <>
                    <p className="lead">
                        This article is currently being generated by our editorial team. It will function as a definitive resource for <strong>{post.title}</strong>.
                    </p>
                    <div className="p-4 bg-yellow-50 border border-yellow-200 rounded text-yellow-800">
                        Construction in progress. Please check back soon.
                    </div>
                </>
            )}

        </ArticleTemplate>
    );
}
